# Generated by Django 4.1.5 on 2023-02-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_package_status_package_pid_package_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='est',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
