# Generated by Django 4.1.5 on 2023-02-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_package_date_sent_package_est_alter_status_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='tracking',
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.status'),
        ),
    ]
