# Generated by Django 4.1.5 on 2023-02-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_status_tracking_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
        migrations.AddField(
            model_name='package',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='status_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='status_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
